import React from 'react';
import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  const { data: session } = useSession();

  const SignedInComponent = () => {
    return (
      <>
        Signed in as {session.user.email} <br />
        <div>You can now acces our super secret pages</div>
        <button>
          <Link href="/secret">To the secret</Link>
        </button>
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  };

  const SignedOutComponent = () => {
    return (
      <>
        Not signed in <br />
        <button onClick={() => signIn()}>Sign in</button>
      </>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {session && <SignedInComponent />}
        {!session && <SignedOutComponent />}
      </main>
    </div>
  );
}
